[server]
fileWatcherType = "none"

[theme]

# Primary accent for interactive elements
primaryColor = '#006EC6'

# Background color for the main content area
backgroundColor = '#FFFFFF'  # White background

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#E9F3FB'  # Material 200 variant of primary color

# Color used for almost all text
textColor = '#002A4B'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
